import { CommonModule } from '@angular/common';
import { Component, Directive, ElementRef, EventEmitter, HostListener, Input, Output, signal } from '@angular/core';
import { createId, nextIndex, type Direction, type Orientation } from '@simurgh-ui/core';

@Directive({ selector: '[simurghTrigger]', standalone: true, exportAs: 'simurghTrigger' })
export class SimurghTrigger { @Input() disabled = false; @Output() activate = new EventEmitter<void>(); @HostListener('click') click() { if (!this.disabled) this.activate.emit(); } }

@Component({ selector: 'simurgh-dialog', standalone: true, imports: [CommonModule], template: `<ng-content select="[trigger]"/><div *ngIf="open" class="simurgh-overlay" (click)="close()"></div><section *ngIf="open" class="simurgh-content simurgh-dialog" role="dialog" aria-modal="true" tabindex="-1" (keydown.escape)="close()"><ng-content/></section>` })
export class DialogComponent { @Input() open = false; @Output() openChange = new EventEmitter<boolean>(); show() { this.open = true; this.openChange.emit(true); } close() { this.open = false; this.openChange.emit(false); } }

abstract class FloatingBase { @Input() open = false; @Output() openChange = new EventEmitter<boolean>(); toggle() { this.open = !this.open; this.openChange.emit(this.open); } close() { this.open = false; this.openChange.emit(false); } }
const floatingTemplate = `<button type="button" class="simurgh-trigger" [attr.aria-expanded]="open" (click)="toggle()"><ng-content select="[trigger]"/></button><div *ngIf="open" class="simurgh-content" style="position:absolute"><ng-content/></div>`;
@Component({ selector: 'simurgh-popover', standalone: true, imports: [CommonModule], template: floatingTemplate }) export class PopoverComponent extends FloatingBase {}
@Component({ selector: 'simurgh-tooltip', standalone: true, imports: [CommonModule], template: `<span (mouseenter)="open=true" (mouseleave)="open=false" (focusin)="open=true" (focusout)="open=false"><ng-content select="[trigger]"/></span><div *ngIf="open" role="tooltip" class="simurgh-content"><ng-content/></div>` }) export class TooltipComponent extends FloatingBase {}
@Component({ selector: 'simurgh-dropdown-menu', standalone: true, imports: [CommonModule], template: `<button type="button" class="simurgh-trigger" aria-haspopup="menu" [attr.aria-expanded]="open" (click)="toggle()"><ng-content select="[trigger]"/></button><div *ngIf="open" role="menu" class="simurgh-content"><ng-content/></div>` }) export class DropdownMenuComponent extends FloatingBase {}
@Directive({ selector: '[simurghMenuItem]', standalone: true, host: { role: 'menuitem', class: 'simurgh-item', tabindex: '-1' } }) export class DropdownMenuItemDirective { @Input() disabled = false; @Output() select = new EventEmitter<void>(); @HostListener('click') onClick() { if (!this.disabled) this.select.emit(); } }

@Component({ selector: 'simurgh-tabs', standalone: true, template: `<div role="tablist" [attr.aria-orientation]="orientation" (keydown)="navigate($event)"><ng-content select="[tab]"/></div><ng-content/>` })
export class TabsComponent { @Input() value = ''; @Input() orientation: Orientation = 'horizontal'; @Input() direction: Direction = 'ltr'; @Output() valueChange = new EventEmitter<string>(); constructor(private element: ElementRef<HTMLElement>) {} select(value: string) { this.value = value; this.valueChange.emit(value); } navigate(event: KeyboardEvent) { const tabs = Array.from(this.element.nativeElement.querySelectorAll<HTMLElement>('[role=tab]')); const i = tabs.indexOf(document.activeElement as HTMLElement); const n = nextIndex(i, tabs.length, event.key, { orientation: this.orientation, direction: this.direction }); if (n !== i) { event.preventDefault(); tabs[n]?.focus(); tabs[n]?.click(); } } }
@Directive({ selector: '[simurghTab]', standalone: true, host: { role: 'tab' } }) export class TabDirective { @Input({ alias: 'simurghTab', required: true }) value = ''; constructor(private tabs: TabsComponent) {} @HostListener('click') select() { this.tabs.select(this.value); } @HostListener('attr.aria-selected') selected() { return this.tabs.value === this.value; } }
@Directive({ selector: '[simurghTabPanel]', standalone: true, host: { role: 'tabpanel' } }) export class TabPanelDirective { @Input({ alias: 'simurghTabPanel', required: true }) value = ''; constructor(public tabs: TabsComponent) {} }

@Component({ selector: 'simurgh-accordion', standalone: true, template: `<ng-content/>` }) export class AccordionComponent { @Input() multiple = false; readonly open = signal<string[]>([]); toggle(value: string) { this.open.update(items => items.includes(value) ? items.filter(x => x !== value) : this.multiple ? [...items, value] : [value]); } }
@Component({ selector: 'simurgh-accordion-item', standalone: true, imports: [CommonModule], template: `<h3><button type="button" [attr.aria-expanded]="expanded" (click)="toggle()"><ng-content select="[trigger]"/></button></h3><div *ngIf="expanded" role="region"><ng-content/></div>` }) export class AccordionItemComponent { @Input({ required: true }) value = ''; constructor(private accordion: AccordionComponent) {} get expanded() { return this.accordion.open().includes(this.value); } toggle() { this.accordion.toggle(this.value); } }

abstract class CheckBase { @Input() checked = false; @Input() disabled = false; @Input() required = false; @Input() name?: string; @Input() value = 'on'; @Output() checkedChange = new EventEmitter<boolean>(); toggle() { if (!this.disabled) { this.checked = !this.checked; this.checkedChange.emit(this.checked); } } }
@Component({ selector: 'simurgh-checkbox', standalone: true, imports: [CommonModule], template: `<button type="button" role="checkbox" [attr.aria-checked]="checked" [disabled]="disabled" (click)="toggle()"><ng-content/></button><input *ngIf="name" hidden type="checkbox" [name]="name" [value]="value" [checked]="checked" [required]="required" [disabled]="disabled">` }) export class CheckboxComponent extends CheckBase {}
@Component({ selector: 'simurgh-switch', standalone: true, imports: [CommonModule], template: `<button type="button" role="switch" [attr.aria-checked]="checked" [disabled]="disabled" (click)="toggle()"><ng-content/></button><input *ngIf="name" hidden type="checkbox" [name]="name" [value]="value" [checked]="checked" [required]="required" [disabled]="disabled">` }) export class SwitchComponent extends CheckBase {}

export type SelectOption = { value: string; label: string; disabled?: boolean };
@Component({ selector: 'simurgh-select', standalone: true, imports: [CommonModule], template: `<button type="button" role="combobox" class="simurgh-trigger" [attr.aria-expanded]="open" [disabled]="disabled" (click)="open=!open">{{label}}</button><div *ngIf="open" role="listbox" class="simurgh-content"><button *ngFor="let option of options" type="button" role="option" class="simurgh-item" [attr.aria-selected]="option.value===value" [disabled]="option.disabled" (click)="select(option.value)">{{option.label}}</button></div><input *ngIf="name" type="hidden" [name]="name" [value]="value" [disabled]="disabled">` })
export class SelectComponent { @Input() options: SelectOption[] = []; @Input() value = ''; @Input() placeholder = 'Select…'; @Input() name?: string; @Input() required = false; @Input() disabled = false; @Output() valueChange = new EventEmitter<string>(); open = false; get label() { return this.options.find(o => o.value === this.value)?.label ?? this.placeholder; } select(value: string) { this.value = value; this.open = false; this.valueChange.emit(value); } }

export type ToastMessage = { id: string; title: string; description?: string };
@Component({ selector: 'simurgh-toast-viewport', standalone: true, imports: [CommonModule], template: `<div class="simurgh-toast-region" aria-label="Notifications"><article *ngFor="let item of messages()" role="status" class="simurgh-content simurgh-toast"><strong>{{item.title}}</strong><p *ngIf="item.description">{{item.description}}</p><button type="button" aria-label="Dismiss notification" (click)="dismiss(item.id)">×</button></article></div>` })
export class ToastViewportComponent { readonly messages = signal<ToastMessage[]>([]); toast(message: Omit<ToastMessage, 'id'>, duration = 5000) { const id = createId('toast'); this.messages.update(items => [...items, { ...message, id }]); if (duration) setTimeout(() => this.dismiss(id), duration); return id; } dismiss(id: string) { this.messages.update(items => items.filter(x => x.id !== id)); } }

export const SIMURGH_COMPONENTS = [DialogComponent, PopoverComponent, TooltipComponent, DropdownMenuComponent, TabsComponent, AccordionComponent, AccordionItemComponent, CheckboxComponent, SwitchComponent, SelectComponent, ToastViewportComponent] as const;
