// Generated by scripts/generate-entrypoints.mjs.
export {
  SidebarProviderComponent,
  SidebarDirective,
  SidebarTriggerDirective,
  SidebarHeaderDirective,
  SidebarContentDirective,
  SidebarFooterDirective,
  SidebarGroupDirective,
  SidebarMenuDirective,
} from '../index.js';
